-- sibyl_plugin.* schema v1
--
-- Plugin account system + activation flow + growth telemetry. Lives on the
-- same Neon Postgres instance as sibyl_memory.* but in its own namespace.
--
-- Holds ONLY account-level data (identity, tier, sessions, events). Memory
-- content stays on the user's local SQLite. The local-first promise is
-- structurally enforced by the fact that this schema has no memory tables.
--
-- 7 tables: accounts | sessions | tier_assignments | activations_log |
--           telemetry_events | funnel_events | machine_fingerprints
--
-- Idempotent. Wrapped in a single transaction. Maximum-defensible data
-- collection scope per operator directive 2026-05-15 (everything that helps
-- growth without compromising the local-first memory-content promise).

BEGIN;

CREATE SCHEMA IF NOT EXISTS sibyl_plugin;
SET search_path TO sibyl_plugin, public;

-- ============================================================================
-- accounts: the primary customer record
-- ============================================================================
CREATE TABLE IF NOT EXISTS sibyl_plugin.accounts (
  account_id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- identity (at least one of email / wallet must be set)
  email                   TEXT,
  wallet                  TEXT,  -- normalized to lowercase
  siwe_handle             TEXT,  -- X or farcaster handle resolved from wallet, if any

  -- attribution
  source                  TEXT,  -- referrer or campaign tag at activation time
  utm_source              TEXT,
  utm_medium              TEXT,
  utm_campaign            TEXT,
  install_method          TEXT,  -- curl-bash / pip / win-iwr / docker / etc

  -- environment (snapshot at first activation)
  os_family               TEXT,  -- macos / linux / windows / container
  os_version              TEXT,
  python_version          TEXT,
  hermes_version          TEXT,
  arch                    TEXT,  -- arm64 / x86_64

  -- geo (country-level only via IP geolocation)
  country_code            TEXT,
  region                  TEXT,

  -- tier
  tier                    TEXT NOT NULL DEFAULT 'free',
  tier_changed_at         TIMESTAMPTZ,

  -- engagement signals
  last_seen_at            TIMESTAMPTZ,
  total_activations       INT NOT NULL DEFAULT 1,
  cap_warning_seen_at     TIMESTAMPTZ,
  upgrade_prompt_clicks   INT NOT NULL DEFAULT 0,

  -- privacy
  telemetry_opt_in        BOOLEAN NOT NULL DEFAULT TRUE,
  deleted_at              TIMESTAMPTZ,  -- soft delete for GDPR

  CONSTRAINT accounts_identity_present CHECK (email IS NOT NULL OR wallet IS NOT NULL),
  CONSTRAINT accounts_tier_valid CHECK (tier IN ('free', 'sync', 'team', 'lifetime', 'stake', 'enterprise'))
);

-- Email + wallet are independently unique (a user can't have two accounts on
-- the same email, but can have one email account and one wallet account if
-- they choose).
CREATE UNIQUE INDEX IF NOT EXISTS accounts_email_unique
  ON sibyl_plugin.accounts (email) WHERE email IS NOT NULL AND deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS accounts_wallet_unique
  ON sibyl_plugin.accounts (wallet) WHERE wallet IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS accounts_tier ON sibyl_plugin.accounts (tier);
CREATE INDEX IF NOT EXISTS accounts_last_seen ON sibyl_plugin.accounts (last_seen_at DESC);
CREATE INDEX IF NOT EXISTS accounts_country ON sibyl_plugin.accounts (country_code);

-- ============================================================================
-- sessions: activation flow state (token -> account binding)
-- ============================================================================
CREATE TABLE IF NOT EXISTS sibyl_plugin.sessions (
  session_token   UUID PRIMARY KEY,  -- generated by plugin
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at      TIMESTAMPTZ NOT NULL,  -- typically created_at + 24h
  bound_to        UUID REFERENCES sibyl_plugin.accounts(account_id) ON DELETE CASCADE,
  bound_at        TIMESTAMPTZ,
  ip              TEXT,
  user_agent      TEXT
);

CREATE INDEX IF NOT EXISTS sessions_expires ON sibyl_plugin.sessions (expires_at);
CREATE INDEX IF NOT EXISTS sessions_bound_to ON sibyl_plugin.sessions (bound_to);

-- ============================================================================
-- tier_assignments: tier change history with timestamps
-- ============================================================================
CREATE TABLE IF NOT EXISTS sibyl_plugin.tier_assignments (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id  UUID NOT NULL REFERENCES sibyl_plugin.accounts(account_id) ON DELETE CASCADE,
  from_tier   TEXT,
  to_tier     TEXT NOT NULL,
  changed_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  reason      TEXT,  -- 'signup' / 'upgrade-cloud' / 'upgrade-lifetime' / 'upgrade-stake' / 'downgrade-cancel'
  metadata    JSONB
);

CREATE INDEX IF NOT EXISTS tier_assignments_account
  ON sibyl_plugin.tier_assignments (account_id, changed_at DESC);

-- ============================================================================
-- activations_log: immutable audit of every activation event
-- ============================================================================
CREATE TABLE IF NOT EXISTS sibyl_plugin.activations_log (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id  UUID REFERENCES sibyl_plugin.accounts(account_id) ON DELETE SET NULL,
  ts          TIMESTAMPTZ NOT NULL DEFAULT now(),
  event_type  TEXT NOT NULL,  -- 'first_activation' / 're_activation' / 'pause' / 'resume' / 'revoke'
  ip          TEXT,
  user_agent  TEXT,
  metadata    JSONB
);

CREATE INDEX IF NOT EXISTS activations_log_account
  ON sibyl_plugin.activations_log (account_id, ts DESC);
CREATE INDEX IF NOT EXISTS activations_log_ts
  ON sibyl_plugin.activations_log (ts DESC);
CREATE INDEX IF NOT EXISTS activations_log_event_type
  ON sibyl_plugin.activations_log (event_type, ts DESC);

-- ============================================================================
-- telemetry_events: heartbeat payloads (engagement, capacity, multi-machine)
-- ============================================================================
CREATE TABLE IF NOT EXISTS sibyl_plugin.telemetry_events (
  event_id    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id  UUID NOT NULL REFERENCES sibyl_plugin.accounts(account_id) ON DELETE CASCADE,
  ts          TIMESTAMPTZ NOT NULL DEFAULT now(),
  event_type  TEXT NOT NULL,  -- 'heartbeat' / 'cap_warning' / 'upgrade_prompt_seen' / 'dormancy_signal' / 'uninstall'
  payload     JSONB
);

CREATE INDEX IF NOT EXISTS telemetry_events_account_ts
  ON sibyl_plugin.telemetry_events (account_id, ts DESC);
CREATE INDEX IF NOT EXISTS telemetry_events_type
  ON sibyl_plugin.telemetry_events (event_type, ts DESC);

-- ============================================================================
-- funnel_events: stage transitions in the conversion funnel
-- ============================================================================
CREATE TABLE IF NOT EXISTS sibyl_plugin.funnel_events (
  event_id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id      UUID REFERENCES sibyl_plugin.accounts(account_id) ON DELETE CASCADE,
  session_token   UUID REFERENCES sibyl_plugin.sessions(session_token) ON DELETE SET NULL,
  ts              TIMESTAMPTZ NOT NULL DEFAULT now(),
  stage           TEXT NOT NULL,  -- 'pip_installed' / 'init_started' / 'browser_opened' / 'auth_completed' / 'first_write' / 'cap_warning_seen' / 'upgrade_prompt_clicked' / 'upgrade_completed' / 'dormant_30d'
  metadata        JSONB
);

CREATE INDEX IF NOT EXISTS funnel_events_account_ts
  ON sibyl_plugin.funnel_events (account_id, ts DESC);
CREATE INDEX IF NOT EXISTS funnel_events_stage_ts
  ON sibyl_plugin.funnel_events (stage, ts DESC);

-- ============================================================================
-- machine_fingerprints: stable per-machine identifiers (multi-machine signal)
-- ============================================================================
CREATE TABLE IF NOT EXISTS sibyl_plugin.machine_fingerprints (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id      UUID NOT NULL REFERENCES sibyl_plugin.accounts(account_id) ON DELETE CASCADE,
  fingerprint     TEXT NOT NULL,  -- salted hash of (OS + arch + install_path + machine_id)
  first_seen_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  os_info         JSONB,  -- {os_family, os_version, arch, ...}
  UNIQUE (account_id, fingerprint)
);

CREATE INDEX IF NOT EXISTS machine_fingerprints_account
  ON sibyl_plugin.machine_fingerprints (account_id);

-- ============================================================================
-- Schema version tracking
-- ============================================================================
CREATE TABLE IF NOT EXISTS sibyl_plugin.schema_version (
  version       INT PRIMARY KEY,
  applied_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  description   TEXT
);

INSERT INTO sibyl_plugin.schema_version (version, description)
VALUES (1, 'Initial sibyl_plugin.* schema. 7 tables (accounts, sessions, tier_assignments, activations_log, telemetry_events, funnel_events, machine_fingerprints). Maximum-defensible data collection per 2026-05-15 operator directive. No memory content stored — local-first promise structurally enforced. RLS policies deferred until first external tenant.')
ON CONFLICT (version) DO NOTHING;

COMMIT;
