-- sibyl_plugin.* schema v4
--
-- Replaces the Resend-based email-magic-code path with terminal pairing
-- codes generated by the CLI. The 6-digit code is created locally by
-- `sibyl init`, printed in the user's terminal, sent (hashed) to the
-- server via /api/plugin/session-init, and typed into the browser as
-- proof of co-presence between the two devices.
--
-- No external email service required. No domain verification, no API key,
-- no spam-folder failures. The whole flow happens between the user's
-- terminal, their browser, and the server.
--
-- Idempotent. Safe to re-run.
--
-- The v3 email_codes table is left in place (currently zero rows) as
-- immutable record. New code paths do not write to it.

BEGIN;
SET search_path TO sibyl_plugin, public;

ALTER TABLE sibyl_plugin.sessions ADD COLUMN IF NOT EXISTS pairing_code_hash      TEXT;
ALTER TABLE sibyl_plugin.sessions ADD COLUMN IF NOT EXISTS pairing_code_attempts  INT NOT NULL DEFAULT 0;
ALTER TABLE sibyl_plugin.sessions ADD COLUMN IF NOT EXISTS pairing_code_expires_at TIMESTAMPTZ;
ALTER TABLE sibyl_plugin.sessions ADD COLUMN IF NOT EXISTS pairing_code_consumed_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS sessions_pairing_expires
  ON sibyl_plugin.sessions (pairing_code_expires_at)
  WHERE pairing_code_hash IS NOT NULL;

INSERT INTO sibyl_plugin.schema_version (version, description)
VALUES (4, 'Replace Resend-backed email magic-code with terminal pairing codes. CLI generates 6-digit code locally, sends sha256 hash to /session-init. Browser submits code with email to /email-bind. No external email dependency. v3 email_codes table preserved but unused — new code paths write pairing fields on sessions instead. Tier-jacking mitigation: if an account exists with wallet IS NOT NULL, /email-bind refuses and requires SIWE.')
ON CONFLICT (version) DO NOTHING;

COMMIT;
